apiVersion: integration/v1
kind: Step
name: azure-storage-step-account-list
version: 1
summary: List storage accounts

description: This Azure Storage step allows you to list Azure storage accounts

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/azure-storage-step-account-list

schemas:
  spec:
    source: file
    file: spec.schema.json
  output:
    source: file
    file: output.schema.json